# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs'

platform :ios, '14.0'

target 'ClownRoyale' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClownRoyale
  #pod 'TwilioVideo', '~> 4.3'
  pod 'AgoraUIKit'

  target 'ClownRoyaleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClownRoyaleUITests' do
    # Pods for testing
  end

end
