version: '3'

volumes:
  shared_data:
      driver: local
  mysql_data:
      driver: local
  mongodb_data_container:    


services:
  clown_mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
  clown_keycloak_authentication:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./imports/cache_reload/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
      - ./imports/themes/custom/:/opt/jboss/keycloak/themes/custom-theme/
    environment:
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - 8080:8080
    depends_on: 
      - clown_mysql
  clown_databasee:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes: 
      - mongodb_data_container:/data/db  